# AUTOGENERATED FILE - DO NOT EDIT

defmodule UXID.Spec0001Test do
  use ExUnit.Case, async: true
  @moduledoc """
  UXID Spec 0001 - setup api

  Ensure the implementation is setup and that the generated tests will work. Makes sure the correct API is in place.

  """

  @moduletag specgroup: "00"
  @moduletag spec: "0001"


  describe "setup api: api" do


    test "UXID decode exists" do
      result = UXID.decode("01E9VB3RWNAR89HSKMS84K9HCS")
      refute is_nil(result)
    end

  end

  describe "setup api: decoder" do

    test "returns a UXID with input" do
      input_string = "01E9VB3RWNAR89HSKMS84K9HCS"
      result = UXID.Decoder.process(input_string)

      assert {:ok, %UXID{} = uxid} = result
      assert "01E9VB3RWNAR89HSKMS84K9HCS" == uxid.encoded




    end

    test "rejects blank strings" do
      input_string = ""
      result = UXID.Decoder.process(input_string)

      assert {:error, message} = result
      assert "input is required" == message

    end

  end
end
